image: mbrainiac/electron-builder:latest

cache:
  paths:
  - node_modules
  - app/node_modules
  - .electron-cache

before_script:

stages:
  - prepare
  - build

prepare_job:
  stage: prepare
  script:
    - sudo npm install
    - npm run install-app-deps

build_linux:
  stage: build
  script:
    - npm run dist:linux
    - mkdir -p ./dist/linux
    - tar -czvf ./dist/Pencil-linux-x64.tar.gz -C ./dist/Pencil-linux-x64 .
    - cp -rf ./dist/*.gz ./dist/linux
    - cp -rf ./dist/*.deb ./dist/linux
  artifacts:
    paths:
    - dist/linux
  only:
    - master@evolus/pencil

build_win32:
  stage: build
  script:
    - npm run dist:win32
  artifacts:
    paths:
    - dist/win
    - dist/win-x64
  only:
    - master@evolus/pencil

# build_darwin:
#   stage: build
#   script:
#     - npm run dist:darwin
#     - mkdir -p ./dist/darwin
#     - cp -rf ./dist/*.zip ./dist/darwin
#   artifacts:
#     paths:
#     - dist/darwin
