osx_image: xcode7.3

sudo: required
dist: trusty


env:
  global:
    - NODE_VERSION=5.10.0
    - USE_SYSTEM_FPM=true
    - secure: E0ghqUHn8cFewr+wYJgnLSpn/e+3RPhnoLNAYMuhpGhPtpVgmlTqb7oqHHLVOjQtfDEp495tMolYeaJZaqGAC4RnEPtn664wrgoEI+FLegNV3SJx+oFF53LmT3zZnwVhbF6J3ZwF8QLYPKad5PcCqVo8SMvMMyWD5m6TzJFJ+1caNi6wJrKkQBqHtCkKOkazp0ZXwpl1SVQl24bofCZfGn7zbmRJ0+VXvfeg1GqkF1GFqkDKc2SkGQn9VUH1d2ejahWxV3dH+VPuyqUuTlPIrv7TjUU4OH9hr3mjQPtWMOnvK0BzOQKu2B9tpAUHbuT5z74TSc7TYQjDA0zQG02h1ALll0Fm+9UOYJQZMidNNiawCDXx1a0Fu+SLWNK9KX/R3FD2ip4wVKKjl/DyTy5Nnw/BsWX4UkYijW3IuegV7a0UokISD6OJqLeo+gmmNon2ngxum+Av1veB/z9c/zZanQwx+CumeqAD7eHCbxZv+bwMAFfsoC6Bv6CtTlU+uBeu7wSUyMxVzaW8qF+MbeMboG3ht12+K6Xxdp+C26eGbkQr7YlITumy5glhd4jlCAxI+DT1uZAWPnIfdOtRWUPd78ABy9G3y98ppnlqCNPbxShI3Tgtp8mTDEpM0znVnZOXcQFzrEX7r2IsGmnIuoUf77lmdpuDTYPq6KAbAOtkjCE=
    - secure: XRU4DwrO+LH9AIPkcIlcRcmU3Fme+XN4wdDKYLo2obNQHlSod+UjqNGjr3SfzXV5JUVavp+ZsJS3+JnFGgz5m3qTVJJLEYZPB9OyqZaz0axacog0LGjTegC55DKwIWLK1Vr7H4lClcS+WJHvRnbyjyUNbPwyurmwrPX0uurd55zZ7yQeFy7XfeEdzc6xRD7Pfivh55o2NcGYUmuOaEeV6f52qqQ84IPUmSnTS8KWuf1+F81HQGLHBtj9hgFta+C0JLzAYkZJsZmfty2SILg4lwqcyjCwVjhGpyLHdRer9phSk353GK2l/SUshaGwfsdqAvRJ3eMq9YRrnELGm9EgoCcMQpwb8R8NPuK9Ou/K3H6k+faaYDOJCHZaM1RsZ1CTTenHDX54kj+EqJi0uLcyWOSSeLM/mQ9KC1RcbnTxanuUSAgjAZT1+16wds5F4Yx39yHVsWfwkNByrHUdGQXLXIbUy7Rdjh/HN/TdLWWlP2N6aw4jEhB0Xc/aN1Yfwai4LTDwTnMv1+b4zKYx/jG6mVgis5CdPAHZwMherPNSBUnQdycMeER7oZyZ1GtVpjSwkSStTDLVj4w7LI4tj6bCPR/tIDwuFy0zVV+5O4sMbHlW3NHRbVu5FOBKoYp0AIMoTdcYMMkyGceM9R9YaL0UsBKkoYYGUnpG5XMvydGctPA=

language: c

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

cache:
  apt: true
  bundler: true
  directories:
    - node_modules
    - .electron-cache
    - $HOME/.electron

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7
      - graphicsmagick
      - xz-utils

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y ruby-dev gcc make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install --no-ri --no-rdoc fpm; fi

install:
  - nvm install $NODE_VERSION
  - npm install npm -g
  - npm install electron-builder@next
  - npm install
  - npm prune

script:
  - npm run dist

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+(\\-.*)?$/"
